/**
 * UserApi
 * API 发布管理
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/weicracker/swagger-yaml-to-d.ts
 * Do not edit the class manually.
 */
/*
/// <reference types="request" />
/// <reference types="bluebird" />
/// <reference types="node" />
/// <reference types="http" />
*/
declare namespace UserApi {
    //重置密码手机方式vo
    interface ResetPwsVO {
        'newPwd': string;
        'telConfirmCode': string;
        'telNum': string;
    }
    //账号信息vo
    interface ReCofingVO {
        //账号的注册形式（手机、邮箱）
        'type': string;
        //账号的注册值
        'typeValue': string;
        //账号所属的用户类型
        'userType': string;
    }
    //查找当前用户关注的好友
    interface ConcernVO {
        //关注的好友Id
        'concernId': string;
        //Id
        'id': string;
        //用戶Id
        'userId': string;
    }
    //群组IdVO
    interface GroupIdVO {
        //Id
        'id': string;
    }
    //获取用户的的好友VO
    interface UserFriend1VO {
        //Id
        'id': string;
        //头像
        'img': string;
        //姓名
        'name': string;
        //个性签名
        'perSignature': string;
    }
    //当前登录用户的组织信息VO
    interface Org1VO {
        //组织中的部门信息
        'department': Array < Org1VO > ;
        //组织头像
        'img': string;
        //组织营业执照照片
        'imgLaw': string;
        //组织Id
        'orgId': string;
        //组织名称
        'orgName': string;
        //组织父节点Id
        'parentId': string;
        //组织纳税登记号
        'payId': string;
    }
    //根据用户姓名或用户登录名查询用户的详细信息VO
    interface CurrUserNameVO {
        //邮箱
        'email': string;
        //头像
        'img': string;
        //姓名
        'name': string;
        //电话
        'tel': string;
        //类型
        'type': string;
        //账号
        'userCode': string;
        //Id
        'userId': string;
    }
    //邮箱VO
    interface EmailVO {
        //邮箱
        'email': string;
    }
    //用户密码修改
    interface UserPassword {
        //新密码
        'newPwd': string;
        //旧密码
        'oldPwd': string;
    }
    //用户code
    interface UserCodeVO {
        //用户code
        'userCode': string;
    }
    //当前登录用户的组织信息VO
    interface OrgUser1VO {
        //组织中的部门信息
        'department': Array < Org1VO > ;
        //是否是管理员
        'ifAdmin': string;
        //组织注册地址
        'orgAddress': string;
        //组织Id
        'orgId': string;
        //组织头像
        'orgImg': string;
        //组织营业执照照片
        'orgImgLaw': string;
        //组织名称
        'orgName': string;
        //组织营业执照号码
        'orgNumber': string;
        //组织父节点Id
        'orgParentId': string;
        //组织纳税登记号
        'orgPayId': string;
        //组织电话号码
        'orgTel': string;
    }
    //用户code
    interface UserCode1VO {
        //用户code
        'code': string;
        //code名称
        'codename': string;
        //id
        'id': string;
    }
    //用户信息与组织信息
    interface UserOrgVO {
        //身份证号
        'cardId': string;
        //身份证正面照片
        'cardIdImg1': string;
        //身份证反面照片
        'cardIdImg2': string;
        //用户真实姓名
        'cardIdName': string;
        //验证码
        'confirmCode': string;
        //用户的邮箱
        'email': string;
        //是否为管理员，1：是，0：否
        'ifAdmin': string;
        //用户头像
        'img': string;
        //是否在线
        'online': string;
        //组织注册地址
        'orgAddress': string;
        //组织ID
        'orgId': string;
        //组织头像信息
        'orgImg': string;
        //组织营业执照照片
        'orgImgLaw': string;
        //组织机构的名称
        'orgName': string;
        //组织营业执照号码
        'orgNumber': string;
        //组织机构上级组织
        'orgParentId': string;
        //组织纳税登记号
        'orgPayId': string;
        //组织电话号码
        'orgTel': string;
        //用户个性签名
        'perSignature': string;
        //用户的手机号码
        'tel': string;
        //个人用户还是企业用户
        'type': string;
        //用户登录名
        'userCode': string;
        //用户ID
        'userId': string;
        //用户昵称
        'userName': string;
        //密码
        'userPassword': string;
    }
    //用户信息
    interface User {
        //身份证号
        'cardId': string;
        //身份证正面照片
        'cardIdImg1': string;
        //身份证反面照片
        'cardIdImg2': string;
        //用户真实姓名
        'cardIdName': string;
        //验证码
        'confirmCode': string;
        //用户的邮箱
        'email': string;
        //用户头像
        'img': string;
        //是否在线
        'online': string;
        //用户个性签名
        'perSignature': string;
        //用户的手机号码
        'tel': string;
        //个人用户还是企业用户
        'type': string;
        //账号
        'userCode': string;
        //用户ID
        'userId': string;
        //用户名（昵称）
        'userName': string;
        //密码
        'userPassword': string;
    }
    //用户好友群组
    interface Frgroup {
        //成员数量（系统自动生成）
        'count': string;
        //创建时间（系统自动生成）
        'createtime': string;
        //创建者（系统自动生成）
        'creator': string;
        //群组ID（系统自动生成）
        'id': string;
        //群组图标
        'img': string;
        //是否被逻辑删除（yes,no）
        'logicDelete': string;
        //名称
        'name': string;
        //修改时间（系统自动生成）
        'updatatime': string;
    }
    //获取用户的的好友VO
    interface UserFriendVO {
        //Id
        'id': string;
        //头像
        'img': string;
        //姓名
        'name': string;
    }
    //获取当前登录用户的组织获取父节点组织VO
    interface OrgOnlyVO {
        //头像
        'img': string;
        //Id
        'orgId': string;
        //名称
        'orgName': string;
        //父节点Id
        'parentId': string;
    }
    //群组成员VO
    interface FrgroupMemberVO {
        //对话
        'conversation': string;
        //创建时间
        'createtime': string;
        //群组Id
        'groupid': string;
        //Id
        'id': string;
        //头像
        'img': string;
        //成员别名
        'memberAlias': string;
        //成员Id
        'memberid': string;
        //姓名
        'name': string;
        //权限
        'power': string;
    }
    //微信uriVO
    interface UriVO {
        //微信uri
        'uri': string;
    }
    //当前登录用户的组织信息VO
    interface CurUserOrgInfoVO {
        //是否是管理员
        'ifadmin': string;
        //注册地址
        'orgAddress': string;
        //Id
        'orgId': string;
        //头像
        'orgImg': string;
        //营业执照照片
        'orgImgLaw': string;
        //名称
        'orgName': string;
        //营业执照号码
        'orgNumber': string;
        //父节点Id
        'orgParentId': string;
        //纳税登记号
        'orgPayId': string;
        //电话号码
        'orgTel': string;
    }
    //用戶IdVO
    interface UserIdVO {
        //用戶Id
        'userid': string;
    }
    //好友分组VO
    interface GroupVO {
        //数量
        'count': string;
        //创建时间
        'createtime': string;
        //创建者
        'creator': string;
        //Id
        'id': string;
        //头像
        'img': string;
        //姓名
        'name': string;
    }
    //当前登录用户的基本信息VO
    interface CurUserInfoVO {
        //身份证号
        'cardId': string;
        //身份证正面照片
        'cardIdImg1': string;
        //身份证反面照片
        'cardIdImg2': string;
        //身份证姓名
        'cardIdName': string;
        //是否改变
        'changes': string;
        //邮箱
        'email': string;
        //头像
        'img': string;
        //姓名
        'name': string;
        //当前登录用户的组织信息
        'org': Array < CurUserOrgInfoVO > ;
        //个性签名
        'perSignature': string;
        //电话
        'tel': string;
        //类型
        'type': string;
        //账号
        'userCode': string;
        //Id
        'userId': string;
    }
    //当前登录用户的组织信息VO
    interface OrgVO {
        //是否是管理员
        'ifAdmin': string;
        //头像
        'img': string;
        //Id
        'orgId': string;
        //名称
        'orgName': string;
        //企业是否同意用户加入(&#39;0&#39;:默认)(&#39;1&#39;:同意)(&#39;2&#39;:拒绝)
        'statusOrg': string;
        //类型
        'type': string;
    }
    //获取当前登录用户的组织VO
    interface OrgPeo1VO {
        //Id
        'id': string;
        //头像
        'img': string;
        //姓名
        'name': string;
    }
}